CREATE TABLE IF NOT EXISTS `rl_tiga_titik_tiga_satusehat` (
  `id` int NOT NULL AUTO_INCREMENT,
  `month_year` varchar(7) NOT NULL,
  `ihs_organization` varchar(50) NOT NULL,
  `kategori` varchar(100) NOT NULL,
  `jenis_pelayanan` varchar(150) NOT NULL,
  `total_pasien_rujukan` int NOT NULL DEFAULT 0,
  `total_pasien_non_rujukan` int NOT NULL DEFAULT 0,
  `tindak_lanjut_dirawat` int NOT NULL DEFAULT 0,
  `tindak_lanjut_dirujuk` int NOT NULL DEFAULT 0,
  `tindak_lanjut_pulang` int NOT NULL DEFAULT 0,
  `mati_di_igd_laki_laki` int NOT NULL DEFAULT 0,
  `mati_di_igd_perempuan` int NOT NULL DEFAULT 0,
  `doa_laki_laki` int NOT NULL DEFAULT 0,
  `doa_perempuan` int NOT NULL DEFAULT 0,
  `luka_luka_laki_laki` int NOT NULL DEFAULT 0,
  `luka_luka_perempuan` int NOT NULL DEFAULT 0,
  `false_emergency` int NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_rl33` (`month_year`, `ihs_organization`, `kategori`, `jenis_pelayanan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
